package com.motors.velocity.carbookingservice.model;

public enum ErrorCode {
    STATUS_REQUIRED,
    STARTED_AT_REQUIRED,

    END_DATE_SHORTER_THAN_START_DATE,
    MAX_RENTAL_DAYS_EXCEEDED,

    VEHICLE_ID_REQUIRED,
    VEHICLE_NOT_FOUND,
    VEHICLE_UNAVAILABLE,

    INTERNAL_SERVER_ERROR,
    DATA_INTEGRITY_VIOLATION,
    MALFORMED_REQUEST,
    VALIDATION_FAILED,
}
