package com.motors.velocity.carbookingservice.model;

public enum ErrorCode {
    MAX_RENTAL_DAYS_EXCEEDED,

    INVALID_RENTAL_PERIOD,

    VEHICLE_NOT_FOUND,
    VEHICLE_UNAVAILABLE,

    INTERNAL_SERVER_ERROR,
    DATA_INTEGRITY_VIOLATION,
    MALFORMED_REQUEST,
    VALIDATION_FAILED,

    PAYMENT_REFERENCE_REQUIRED,
    PAYMENT_NOT_APPROVED,
    PAYMENT_REFERENCE_INVALID,
    PAYMENT_NOT_FOUND,
    PAYMENT_SERVICE_UNAVAILABLE,

    INVALID_PAYMENT_SERVICE_RESPONSE,
}
