spring:
  application:
    name: car-booking-service
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:35432/velocity-motors-carrental
    username: booking-service
    password: sachin_hs_123
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    validate-on-migrate: true

credit-card-payment:
  base-url: http://localhost:9090/credit-card-payment-api

