spring:
  application:
    name: car-booking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/velocity-motors-carrental}
    username: ${SPRING_DATASOURCE_USERNAME:booking-service}
    password: ${SPRING_DATASOURCE_PASSWORD:sachin_hs_123}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    validate-on-migrate: true

credit-card-payment:
  base-url: http://localhost:9090/credit-card-payment-api